### PR TITLE
Add MetalLB logo as icon

### PR DESCRIPTION
**Pull request by camille-rodriguez**
chamhub.io displays an icon for each charm, and the icon is missing for both charms metallb-controller and metallb-speaker

### CODE REVIEW

**Comment by camille-rodriguez** [comment]
Side note : I've tried removing the history of all commits from this PR but no can do. Might as well merge all commits into one for this PR upon merge.

**Comment by camille-rodriguez** [comment]
@johnsca can we re-run the tests ? I do not see a valid reason for this failure.

**Comment by evilnick** [comment]
@camille-rodriguez I re-ran the tests there for you but it still seems to be failing

**Review by johnsca — APPROVED** [review]
LGTM.  Test failure seems to be an RBAC issue, but unrelated to this change:

```
E0122 19:08:58.380915       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.ConfigMap: configmaps "config" is forbidden: User "system:serviceaccount:metallb-system:metallb-controller" cannot list resource "configmaps" in API group "" in the namespace "metallb-system"
```

I'm up for merging this but the root of this failure should be investigated, as it doesn't seem likely to go away on its own.

**Pull request merged**
